[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  { name="Mark Aron Szulyovszky", email="mark.szulyovszky@gmail.com" },
  { name="Daniel Szemerey", email="daniel@szemerey.eu" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "numpy",
  "https://github.com/dream-faster/drift/archive/main.zip",
]
description = "Model wrappers for drift."
dynamic = ["version"]
keywords = []
license = "MIT"
name = "drift-models"
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
Documentation = "https://dream-faster.github.io/drift-models"
Issues = "https://github.com/dream-faster/drift-models/issues"
Source = "https://github.com/dream-faster/drift-models"

[tool.hatch.version]
path = "src/drift_models/__init__.py"

[project.optional-dependencies]
quality = [
  "black~=22.10.0",
  "flake8~=4.0.1",
  "isort~=5.10.1",
  "pre-commit~=2.20.0",
]
tests = [
  "pytest~=7.1.2",
]

[tool.hatch.envs.quality]
dependencies = [
  "drift-models[quality]",
]
detached = true

[tool.hatch.envs.quality.scripts]
check = [
  "flake8 src tests",
  "black --check --diff --preview src tests",
  "isort --check-only --diff src tests",
]
format = [
  "isort src tests",
  "black --preview src tests",
  "check",
]

[tool.hatch.envs.test]
dependencies = ["drift-models[tests]"]

[tool.hatch.envs.test.scripts]
run = "pytest tests/ --durations 0 -s"

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310"]

[tool.isort]
profile = "black"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
  "/.devcontainer",
  "/.pre-commit-config.yaml",
  "/.gitignore",
  "/tests",
]
